import type {
  ChallengeBadge,
  ChallengeDefinition,
  ChallengeParticipation,
} from './types';

export const CHALLENGE_DEMO_TODAY = '2026-09-13';

export const initialChallengeBadges: ChallengeBadge[] = [
  {
    id: 'badge-walk',
    name: '7일 걷기 배지',
    description: '매일 걷기를 7일 모두 기록했어요.',
    icon: 'check',
    imageUrl: '/images/challenges/badge-walk.png',
    earnedAt: '2026-09-12',
  },
  {
    id: 'badge-pill',
    name: '복약 루틴 배지',
    description: '예정된 복약을 빠짐없이 기록했어요.',
    icon: 'pill',
    imageUrl: '/images/challenges/badge-medication.png',
    earnedAt: '2026-09-07',
  },
  {
    id: 'badge-sprout',
    name: '영양제 루틴 배지',
    description: '영양제 복용 루틴을 꾸준히 이어갔어요.',
    icon: 'sprout',
    imageUrl: '/images/challenges/badge-supplement.png',
    earnedAt: '2026-09-10',
  },
  {
    id: 'badge-first',
    name: '첫 챌린지 배지',
    description: '첫 챌린지를 끝까지 완주하면 받을 수 있어요.',
    icon: 'check',
    imageUrl: '/images/challenges/badge-review.png',
  },
  {
    id: 'badge-review',
    name: '물 마시기 7일 배지',
    description: '정한 물 마시기 목표를 7일 모두 기록하면 받을 수 있어요.',
    icon: 'sprout',
    imageUrl: '/images/challenges/badge-review.png',
  },
  {
    id: 'badge-visit',
    name: '스트레칭 루틴 배지',
    description: '2주 동안 매주 스트레칭 목표를 채우면 받을 수 있어요.',
    icon: 'check',
    imageUrl: '/images/challenges/badge-review.png',
  },
];

export const initialChallengeDefinitions: ChallengeDefinition[] = [
  {
    id: 'official-walk-7d',
    kind: 'official',
    title: '매일 30분 걷기',
    description: '걷기로 채우는 나의 일주일',
    taskLabel: '30분 걷기',
    frequency: { type: 'daily', durationDays: 7 },
    enrollmentStart: '2026-09-01',
    enrollmentEnd: '2026-09-30',
    badgeId: 'badge-walk',
  },
  {
    id: 'official-water-7d',
    kind: 'official',
    title: '물 마시기',
    description: '내 목표만큼 물 마시기',
    taskLabel: '정한 만큼 물 마시기',
    frequency: { type: 'daily', durationDays: 7 },
    enrollmentStart: '2026-09-01',
    enrollmentEnd: '2026-09-30',
    badgeId: 'badge-review',
  },
  {
    id: 'official-stretch-weekly',
    kind: 'official',
    title: '가볍게 스트레칭',
    description: '일주일에 세 번, 몸을 가볍게 깨워요',
    taskLabel: '10분 스트레칭',
    frequency: { type: 'weekly', targetDaysPerWeek: 3, durationWeeks: 2 },
    enrollmentStart: '2026-09-01',
    enrollmentEnd: '2026-09-30',
    badgeId: 'badge-visit',
  },
  {
    id: 'official-ended',
    kind: 'official',
    title: '아침 햇빛 보기',
    description: '아침을 여는 작은 습관',
    taskLabel: '10분 햇빛 보기',
    frequency: { type: 'daily', durationDays: 7 },
    enrollmentStart: '2026-08-01',
    enrollmentEnd: '2026-08-31',
    badgeId: 'badge-sprout',
  },
  {
    id: 'official-walk-achieved-demo',
    kind: 'official',
    title: '저녁 산책 7일',
    description: '지난 완주 기록',
    taskLabel: '저녁 산책',
    frequency: { type: 'daily', durationDays: 7 },
    badgeId: 'badge-walk',
  },
  {
    id: 'official-walk-missed-demo',
    kind: 'official',
    title: '아침 스트레칭 7일',
    description: '지난 도전 기록',
    taskLabel: '아침 스트레칭',
    frequency: { type: 'daily', durationDays: 7 },
  },
  {
    id: 'official-first-finish-demo',
    kind: 'official',
    title: '첫 도전 마무리',
    description: '마지막 한 번의 실천이 남았어요.',
    taskLabel: '오늘의 실천',
    frequency: { type: 'daily', durationDays: 1 },
    badgeId: 'badge-first',
  },
  {
    id: 'medication-routine',
    kind: 'medication',
    title: '복약 루틴',
    description: '홈에서 남긴 복약 기록이 자동으로 반영돼요.',
    taskLabel: '예정된 복약',
    frequency: { type: 'daily', durationDays: 7 },
    badgeId: 'badge-pill',
  },
  {
    id: 'supplement-routine',
    kind: 'supplement',
    title: '영양제 루틴',
    description: '홈에서 남긴 영양제 기록이 자동으로 반영돼요.',
    taskLabel: '영양제 복용',
    frequency: { type: 'daily', durationDays: 7 },
    badgeId: 'badge-sprout',
  },
  {
    id: 'review-records',
    kind: 'review',
    title: '이번 주 기록 돌아보기',
    description: '내가 남긴 건강 기록을 하나씩 확인해요.',
    taskLabel: '건강 기록 확인',
    frequency: { type: 'daily', durationDays: 7 },
  },
  {
    id: 'visit-records',
    kind: 'visit',
    title: '다음 진료 준비하기',
    description: '다가오는 진료 일정을 미리 확인해요.',
    taskLabel: '진료 일정 확인',
    frequency: { type: 'daily', durationDays: 1 },
  },
];

export const initialChallengeParticipations: ChallengeParticipation[] = [
  {
    id: 'part-official-active',
    challengeId: 'official-walk-7d',
    title: '매일 30분 걷기',
    kind: 'official',
    startDate: '2026-09-10',
    endDate: '2026-09-16',
    status: 'active',
    completed: 3,
    target: 7,
    percent: 43,
    todayCompleted: false,
    checkInDates: ['2026-09-10', '2026-09-11', '2026-09-12'],
    badgeId: 'badge-walk',
  },
  {
    id: 'part-medication-active',
    challengeId: 'medication-routine',
    title: '복약 루틴',
    kind: 'medication',
    startDate: '2026-09-07',
    endDate: '2026-09-13',
    status: 'active',
    completed: 6,
    target: 9,
    percent: 67,
    todayCompleted: true,
    checkInDates: ['2026-09-07', '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11', '2026-09-12'],
    badgeId: 'badge-pill',
  },
  {
    id: 'part-supplement-active',
    challengeId: 'supplement-routine',
    title: '영양제 루틴',
    kind: 'supplement',
    startDate: '2026-09-07',
    endDate: '2026-09-13',
    status: 'active',
    completed: 3,
    target: 7,
    percent: 43,
    todayCompleted: true,
    checkInDates: ['2026-09-08', '2026-09-10', '2026-09-12'],
    badgeId: 'badge-sprout',
  },
  {
    id: 'part-review-active',
    challengeId: 'review-records',
    title: '이번 주 기록 돌아보기',
    kind: 'review',
    startDate: '2026-09-13',
    endDate: '2026-09-19',
    status: 'active',
    completed: 0,
    target: 2,
    percent: 0,
    todayCompleted: false,
    checkInDates: [],
    checklist: [
      { id: 'review-medications', label: '복용약 확인', checked: false, destination: 'medications', available: true },
      { id: 'review-supplements', label: '영양제 확인', checked: false, destination: 'supplements', available: true },
      { id: 'review-note', label: '복약 메모 확인', checked: false, destination: 'notes', available: false },
    ],
  },
  {
    id: 'part-official-first-finish',
    challengeId: 'official-first-finish-demo',
    title: '첫 도전 마무리',
    kind: 'official',
    startDate: '2026-09-13',
    endDate: '2026-09-13',
    status: 'active',
    completed: 0,
    target: 1,
    percent: 0,
    todayCompleted: false,
    checkInDates: [],
    badgeId: 'badge-first',
  },
  {
    id: 'part-visit-active',
    challengeId: 'visit-records',
    title: '다음 진료 준비하기',
    kind: 'visit',
    startDate: '2026-09-13',
    endDate: '2026-09-13',
    status: 'active',
    completed: 0,
    target: 1,
    percent: 0,
    todayCompleted: false,
    checkInDates: [],
    checklist: [
      { id: 'visit-followup', label: '다가오는 진료 일정 확인', checked: false, destination: 'visit', available: true },
    ],
  },
  {
    id: 'part-official-achieved',
    challengeId: 'official-walk-achieved-demo',
    title: '저녁 산책 7일',
    kind: 'official',
    startDate: '2026-09-06',
    endDate: '2026-09-12',
    status: 'achieved',
    completed: 7,
    target: 7,
    percent: 100,
    todayCompleted: false,
    checkInDates: ['2026-09-06', '2026-09-07', '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11', '2026-09-12'],
    badgeId: 'badge-walk',
  },
  {
    id: 'part-official-missed',
    challengeId: 'official-walk-missed-demo',
    title: '아침 스트레칭 7일',
    kind: 'official',
    startDate: '2026-08-20',
    endDate: '2026-08-26',
    status: 'missed',
    completed: 4,
    target: 7,
    percent: 57,
    todayCompleted: false,
    checkInDates: ['2026-08-20', '2026-08-21', '2026-08-23', '2026-08-25'],
  },
];
